/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dell-info
 */

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

// import java.util.Vector;
import java.util.List;
import java.util.ArrayList;

// import java.text.DateFormat;
import java.text.MessageFormat;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
// import java.text.SimpleDateFormat;

public class Inscription extends javax.swing.JFrame {
    
    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/projet";
    
    Connection sqlConn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    int q, i, id, deletedItem, updatedItem;

    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
        jPassword.setText("");
        chargerGroupes();
        
        getRootPane().setDefaultButton(Valider);
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "quitApp");
getRootPane().getActionMap().put("quitApp", new AbstractAction() {
    @Override
    public void actionPerformed(ActionEvent e) {
        btnQuitter.doClick(); // Simule un clic sur le bouton Quitter
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFiliere = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSexe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        comboGroupes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Nom");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtNom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 480, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Email");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 480, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Filière");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        txtFiliere.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtFiliere, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 480, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setText("Sexe");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        txtSexe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 480, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("ID groupe");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Inscription");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 475, -1));

        Valider.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Valider.setText("S'inscrire");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel3.add(Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, 60));

        btnQuitter.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });
        jPanel3.add(btnQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, -1, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Password");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jPassword.setText("jPasswordField1");
        jPanel3.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 480, 40));

        comboGroupes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboGroupes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 480, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chargerGroupes() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn, username, password);
        pstmt = sqlConn.prepareStatement("SELECT ID_Groupe FROM groupe");
        rs = pstmt.executeQuery();
        
        comboGroupes.removeAllItems();
        while (rs.next()) {
            comboGroupes.addItem(rs.getString("ID_Groupe"));
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erreur lors du chargement des groupes: " + ex.getMessage());
    } finally {
        try { if (rs != null) rs.close(); } catch (Exception e) {}
        try { if (pstmt != null) pstmt.close(); } catch (Exception e) {}
        try { if (sqlConn != null) sqlConn.close(); } catch (Exception e) {}
    }
}
    
    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            /*
            String checkQuery = "SELECT COUNT(*) FROM etudiant WHERE ID_Etudiant = ?";
            pstmt = sqlConn.prepareStatement(checkQuery);
            pstmt.setString(1, txtIDEtudiant.getText());
            ResultSet rs = pstmt.executeQuery();
    
            if (rs.next()) {
                int count = rs.getInt(1);
                if (count > 0) {
                // L'ID_Etudiant existe déjà
                JOptionPane.showMessageDialog(this, "L'étudiant existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;  // Arrêter l'exécution si l'ID existe déjà
                }
            }
            */
            pstmt = sqlConn.prepareStatement("INSERT INTO etudiant(Nom, Email, Filiere_Precedente, Dans_Un_Groupe, Est_Chef, Sexe, ID_Groupe, password) VALUE(?, ?, ?, ?, ?,?,?, ?)");
            //pstmt.setString(1, txtIDEtudiant.getText());
            pstmt.setString(1, txtNom.getText());
            pstmt.setString(2, txtEmail.getText());
            pstmt.setString(3, txtFiliere.getText());
            pstmt.setInt(4, 0);
            pstmt.setInt(5, 0);
            pstmt.setString(6, txtSexe.getText());
            //pstmt.setString(7, txtIDGroupe.getText());
            pstmt.setString(7, comboGroupes.getSelectedItem().toString());
            pstmt.setString(8, new String(jPassword.getPassword())); // Ligne modifiée
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Inscription éffectuée avec succés.");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private JFrame frame;
    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        frame = new JFrame("Quitter");
        if(JOptionPane.showConfirmDialog(frame, "Voulez-vous vraiment quitter l'application ?", "Gestion d'étudiants",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnQuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inscription inscription = new Inscription();
                inscription.setVisible(true);
                inscription.setLocationRelativeTo(null);;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Valider;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JComboBox<String> comboGroupes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFiliere;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtSexe;
    // End of variables declaration//GEN-END:variables
}
