import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

// import java.util.Vector;
import java.util.List;
import java.util.ArrayList;

// import java.text.DateFormat;
import java.text.MessageFormat;
// import java.text.SimpleDateFormat;

import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;




public class View extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "";
    private static final String dataConn = "jdbc:mysql://localhost:3306/projet";
    
    Connection sqlConn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    
    int q, i, id, deletedItem, updatedItem;
    
    public View() {
        initComponents();
        updateDB();
        
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "quitApp");
getRootPane().getActionMap().put("quitApp", new AbstractAction() {
    @Override
    public void actionPerformed(ActionEvent e) {
        btnQuitter.doClick(); // Simule un clic sur le bouton Quitter
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    //=========================================================== Function ==============================================================
    
    public void updateDB() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pstmt = sqlConn.prepareStatement("SELECT * FROM etudiant");
            
            rs = pstmt.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            DefaultTableModel recordTable = (DefaultTableModel) tableAffichage.getModel();
            recordTable.setRowCount(0);
            
            while(rs.next()) {
                //Vector columnData = new Vector<>(); L'utilisation des vecteurs en Java est obsolète.
                List<Object> columnData = new ArrayList<>();
                for(i=1; i<=q; i++) {
                    /*columnData.add(rs.getString("ID"));
                    columnData.add(rs.getString("id_etudiant"));
                    columnData.add(rs.getString("nom"));
                    columnData.add(rs.getString("prenom"));
                    columnData.add(rs.getString("adresse"));
                    columnData.add(rs.getString("code_postal"));
                    columnData.add(rs.getString("telephone"));*/
                    columnData.add(rs.getObject(i));
                }
                //recordTable.addRow(columnData);
                recordTable.addRow(columnData.toArray());
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur de chargement du driver : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    
    //=========================================================== End Function ==============================================================

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnImprimer = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnViderChamps = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFiliere = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDansGroupe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelephone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAffichage = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtSexe = new javax.swing.JTextField();
        txtIDGroupe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImprimer.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        btnImprimer.setText("Imprimer");
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });
        jPanel2.add(btnImprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 60));

        btnAjouter.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        jPanel2.add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 190, 60));

        btnModifier.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        jPanel2.add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 60));

        btnQuitter.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 190, 60));

        btnSupprimer.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        jPanel2.add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 190, 60));

        btnViderChamps.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViderChamps.setText("Vider les champs");
        btnViderChamps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViderChampsActionPerformed(evt);
            }
        });
        jPanel2.add(btnViderChamps, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 190, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 250, 630));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ID étudiant");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 480, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Nom");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtNom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 480, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Email");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 480, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Filière");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtFiliere.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtFiliere, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 480, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setText("Dans groupe");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtDansGroupe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtDansGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 480, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Est chef");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtTelephone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 480, -1));

        tableAffichage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDetudiant", "Nom", "Email", "Filière", "Dans groupe", "Est chef", "Sexe", "IDgroupe"
            }
        ));
        tableAffichage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAffichageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAffichage);
        if (tableAffichage.getColumnModel().getColumnCount() > 0) {
            tableAffichage.getColumnModel().getColumn(0).setMaxWidth(60);
            tableAffichage.getColumnModel().getColumn(4).setMinWidth(150);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 427, 630, 190));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel8.setText("Sexe");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtSexe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 480, -1));

        txtIDGroupe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel3.add(txtIDGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 480, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("ID groupe");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 690, 630));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Gestionnaire des étudiants");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 27, 960, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
        MessageFormat header = new MessageFormat("Impression en cours");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try {
            tableAffichage.print(JTable.PrintMode.NORMAL, header, footer);
        } catch(java.awt.print.PrinterException ex) {
            System.err.format("Imprimante introuvable", ex.getMessage());
        }
    }//GEN-LAST:event_btnImprimerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pstmt = sqlConn.prepareStatement("UPDATE etudiant SET ID_Etudiant=?, Nom=?, Email=?, Filiere_Precedente=?, Dans_Un_Groupe=?, Est_Chef=?, Sexe=?, ID_Groupe=? WHERE ID_Etudiant="+updatedItem);
            pstmt.setString(1, txtID.getText());
            pstmt.setString(2, txtNom.getText());
            pstmt.setString(3, txtEmail.getText());
            pstmt.setString(4, txtFiliere.getText());
            
            boolean dansGroupe = Boolean.parseBoolean(txtDansGroupe.getText());
            pstmt.setInt(5, dansGroupe ? 1 : 0);  
            //pstmt.setString(5, txtDansGroupe.getText());
            
            boolean estChef = Boolean.parseBoolean(txtTelephone.getText());
            pstmt.setInt(6, estChef ? 1 : 0);  
            //pstmt.setString(6, txtEstChef.getText());
           
            pstmt.setString(7, txtSexe.getText());
            pstmt.setString(8, txtIDGroupe.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Etudiant modifié avec succés.");
            updateDB();
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur de chargement du driver : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private JFrame frame;
    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        frame = new JFrame("Quitter");
        if(JOptionPane.showConfirmDialog(frame, "Voulez-vous vraiment quitter l'application ?", "Gestion d'étudiants",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        DefaultTableModel recordTable = (DefaultTableModel) tableAffichage.getModel();
        int selectedRow = tableAffichage.getSelectedRow();
        
        try {
            id = Integer.parseInt(recordTable.getValueAt(selectedRow, 0).toString());
            deletedItem = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer l'étudiant", "Attention", JOptionPane.YES_NO_OPTION);
            if(deletedItem == JOptionPane.YES_OPTION) {
                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn, username, password);
                pstmt = sqlConn.prepareStatement("DELETE FROM etudiant WHERE ID_Etudiant="+id);
                pstmt.executeUpdate();
                /*
                pstmt = sqlConn.prepareStatement("DELETE FROM etudiant WHERE ID="+?);
                pstmt = setInt(1, id);
                pstmt.executeUpdate();
                */
                JOptionPane.showMessageDialog(this, "Etudiant supprimé avec succés.");
                updateDB();
                
                txtID.setText("");
                txtID.requestFocus();
                txtNom.setText("");
                txtEmail.setText("");
                txtFiliere.setText("");
                txtDansGroupe.setText("");
                txtTelephone.setText("");
                txtSexe.setText("");
                txtIDGroupe.setText("");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur de chargement du driver : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnViderChampsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViderChampsActionPerformed
        txtID.setText("");
        txtNom.setText("");
        txtEmail.setText("");
        txtFiliere.setText("");
        txtDansGroupe.setText("");
        txtTelephone.setText("");
        txtSexe.setText("");
        txtIDGroupe.setText("");
    }//GEN-LAST:event_btnViderChampsActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pstmt = sqlConn.prepareStatement("INSERT INTO etudiant(ID_Etudiant, Nom, Email, Filiere_Precedente, Dans_Un_Groupe, Est_Chef, Sexe, ID_Groupe) VALUE(?, ?, ?, ?, ?, ?,?,?)");
            pstmt.setString(1, txtID.getText());
            pstmt.setString(2, txtNom.getText());
            pstmt.setString(3, txtEmail.getText());
            pstmt.setString(4, txtFiliere.getText());
            pstmt.setString(5, txtDansGroupe.getText());
            pstmt.setString(6, txtTelephone.getText());
            pstmt.setString(7, txtSexe.getText());
            pstmt.setString(8, txtIDGroupe.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Etudiant ajouté avec succés.");
            updateDB();
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur de chargement du driver : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erreur SQL : " + ex.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void tableAffichageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAffichageMouseClicked
         DefaultTableModel recordTable = (DefaultTableModel) tableAffichage.getModel();
         int selectedRow = tableAffichage.getSelectedRow();
         
         //updatedItem = (int)recordTable.getValueAt(selectedRow, 0);
    
         // Vérifiez si une ligne est bien sélectionnée
         if (selectedRow != -1) {
        Object idValue = recordTable.getValueAt(selectedRow, 0);

        // Si l'ID est un Long, vous pouvez le convertir en int
        if (idValue instanceof Long) {
            updatedItem = ((Long) idValue).intValue();
        } else {
            updatedItem = (int) idValue;  // Assurez-vous que c'est un entier
        }
        }
                 
         txtID.setText(recordTable.getValueAt(selectedRow, 0).toString());
         txtNom.setText(recordTable.getValueAt(selectedRow, 1).toString());
         txtEmail.setText(recordTable.getValueAt(selectedRow, 2).toString());
         txtFiliere.setText(recordTable.getValueAt(selectedRow, 3).toString());
         txtDansGroupe.setText(recordTable.getValueAt(selectedRow, 4).toString());
         txtTelephone.setText(recordTable.getValueAt(selectedRow, 5).toString());
         txtSexe.setText(recordTable.getValueAt(selectedRow, 6).toString());
         txtIDGroupe.setText(recordTable.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_tableAffichageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View view = new View();
                view.setVisible(true);
                view.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnViderChamps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAffichage;
    private javax.swing.JTextField txtDansGroupe;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFiliere;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDGroupe;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtSexe;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
